Cleaned up bashrc

diff --git a/bash/bashrc b/bash/bashrc
--- a/bash/bashrc
+++ b/bash/bashrc
@@ -26,8 +26,6 @@ if [ -z "${debian_chroot:-}" ] && [ -r /etc/debian_chroot ]; then
     debian_chroot=$(cat /etc/debian_chroot)
 fi
 
-
-
 if [ -n "$DISPLAY" -a "$TERM" == "xterm"  ]; then
         export TERM=xterm-256color
 fi
@@ -36,7 +34,7 @@ color_prompt=yes
 
 # enable color support of ls and also add handy aliases
 if [ -x /usr/bin/dircolors ]; then
-    test -r ~/.dircolors && eval "$(dircolors -b ~/.dircolors)" || eval "$(dircolors -b)"
+    test -r ~/.dir_colors && eval "$(dircolors -b ~/.dir_colors)" || eval "$(dircolors -b)"
     alias ls='ls -h --color=auto'
     alias dir='dir --color=auto'
     alias vdir='vdir --color=auto'
@@ -45,11 +43,6 @@ if [ -x /usr/bin/dircolors ]; then
     alias fgrep='fgrep --color=auto'
     alias egrep='egrep --color=auto'
 fi
-
-# some more ls aliases
-alias ll='ls -alF'
-alias la='ls -A'
-alias l='ls -CF'
 
 # Alias definitions.
 # You may want to put all your additions into a separate file like
@@ -73,71 +66,69 @@ fi
 
 xmodmap ~/.xmodmaprc
 
-# Color_Off="\033[0m"
-# Red="\033[0;31m"
-# Green="\033[0;32m"
-# Purple="\033[0;35m"
-#
+Color_Off="\033[0m"
+Red="\033[0;31m"
+Green="\033[0;32m"
+Purple="\033[0;35m"
+
 # ####-Bold-####
-# BRed="\033[1;31m"
-# BPurple="\033[1;35m"
-#
+BRed="\033[1;31m"
+BPurple="\033[1;35m"
+
 # # Status of last command (for prompt)
-# function __stat() {
-#     if [ $? -eq 0 ]; then
-#         echo -en "$Green[✔]$Color_Off"
-#     else
-#         echo -en "$Red[✘]$Color_Off"
-#     fi
-# }
+function __stat() {
+    if [ $? -eq 0 ]; then
+        echo -en "$Green[✔]$Color_Off"
+    else
+        echo -en "$Red[✘]$Color_Off"
+    fi
+}
 
 
 # Display the branch name of git repository
 # Green -> clean
 # purple -> untracked files
 # red -> files to commit
-# function __git_prompt() {
-#
-#     local git_status="`git status -unormal 2>&1`"
-#
-#     if ! [[ "$git_status" =~ Not\ a\ git\ repo ]]; then
-#         if [[ "$git_status" =~ nothing\ to\ commit ]]; then
-#             local Color_On=$Green
-#         elif [[ "$git_status" =~ nothing\ added\ to\ commit\ but\ untracked\ files\ present ]]; then
-#             local Color_On=$Purple
-#         else
-#             local Color_On=$Red
-#         fi
-#
-#         if [[ "$git_status" =~ On\ branch\ ([^[:space:]]+) ]]; then
-#             branch=${BASH_REMATCH[1]}
-#         else
-#             # Detached HEAD. (branch=HEAD is a faster alternative.)
-#             branch="(`git describe --all --contains --abbrev=4 HEAD 2> /dev/null || echo HEAD`)"
-#         fi
-#
-#         echo -ne "$Color_On[$branch]$Color_Off "
-#     fi
-# }
-#
-# PS1=""
-# # command status (shows check-mark or red x if last command failed)
-# PS1+='$(__stat) '$Color_Off
-#
-# # debian chroot stuff (take it or leave it)
-# PS1+="${debian_chroot:+($debian_chroot)}"
-#
-# # basic information (user@host:path)
-# PS1+="$BRed\u$Color_Off@$BRed\h$Color_Off:$BPurple\w$Color_Off "
-#
-# # add git display to prompt
-# PS1+='$(__git_prompt)'$Color_Off
-#
-# # prompt $ or # for root
-# PS1+="\n \$ "
-# export PS1
+function __git_prompt() {
 
-eval `dircolors ~/.dir_colors`
+    local git_status="`git status -unormal 2>&1`"
+
+    if ! [[ "$git_status" =~ Not\ a\ git\ repo ]]; then
+        if [[ "$git_status" =~ nothing\ to\ commit ]]; then
+            local Color_On=$Green
+        elif [[ "$git_status" =~ nothing\ added\ to\ commit\ but\ untracked\ files\ present ]]; then
+            local Color_On=$Purple
+        else
+            local Color_On=$Red
+        fi
+
+        if [[ "$git_status" =~ On\ branch\ ([^[:space:]]+) ]]; then
+            branch=${BASH_REMATCH[1]}
+        else
+            # Detached HEAD. (branch=HEAD is a faster alternative.)
+            branch="(`git describe --all --contains --abbrev=4 HEAD 2> /dev/null || echo HEAD`)"
+        fi
+
+        echo -ne "$Color_On[$branch]$Color_Off "
+    fi
+}
+
+PS1=""
+# command status (shows check-mark or red x if last command failed)
+PS1+='$(__stat) '$Color_Off
+
+# debian chroot stuff (take it or leave it)
+PS1+="${debian_chroot:+($debian_chroot)}"
+
+# basic information (user@host:path)
+PS1+="$BRed\u$Color_Off@$BRed\h$Color_Off:$BPurple\w$Color_Off "
+
+# add git display to prompt
+PS1+='$(__git_prompt)'$Color_Off
+
+# prompt $ or # for root
+PS1+="\n \$ "
+export PS1
 
 # Added for Extraction
 extract () {
@@ -166,7 +157,3 @@ export EDITOR='vim'
 
 source ~/Doc/repos/tmuxinator/completion/tmuxinator.bash
 source ~/.shell_prompt.sh
-
-if [ -d "$HOME/bin" ] ; then
-    PATH="$HOME/bin:$PATH"
-fi
